### ISSUE TITLE
Node List Improvements

### ISSUE THREAD

**Issue by brngates98** [tiithansen/grafana-k8s-app#31]
It would be awesome instead of the nodes listed by ip to be listed by hostname, with the ip in another column
![Screenshot 2024-07-09 at 12 38 01 PM](https://github.com/tiithansen/grafana-k8s-app/assets/59444489/593e2d91-5194-4652-9ee7-dac9cf39fc77)

**Comment by tiithansen** [comment]
I'll have a look how to include host name. The IP was chosen initially because not all node metrics have host label. But it should be doable.
